name: sens-calc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - astropy=5.1
  - Flask=2.2
  - flask-wtf=1.0
  - numpy=1.23
  - pytest=7.2
  - PyYAML=6.0
  - scipy=1.9
  - setuptools=65.5
  - sphinx_rtd_theme=1.1
  - nbsphinx==0.8
  - python-dotenv=0.21