[tool.poetry]
name = "sensitivity_calculator"
version = "0.1.0"
description = ""
authors = ["jtr6 <joanna.ramasawmy@stfc.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
astropy = "^5.1"
numpy = "^1.23"
scipy = "^1.9"
pyyaml = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
